namespace Samples
{
    public enum TestEnum
    {
        Option,
        Option1,
        Option2,
        Option3,
        Option4,
        Option5,
        Option6,
        Option7,
        Option8,
        Option9,
        Option10,
        Option11,
        Option12,
        Option13,
        Option14,
        Option15,
        Option16,
        Option17,
        Option18,
        Option19,
        Option20,
        Option21,
        Option22,
        Option23,
        Option24,
        Option25,
        Option26,
        Option27,
    }
}